name: neurunner
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flame: ^1.6.0
  flame_tiled: ^1.9.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/background/
    - assets/images/enemies/
    - assets/images/player/
    - assets/images/platforms/
    - assets/images/hud/
    - assets/tiles/
